apiid = 2040
apihash = 'b18441a1ff607e10a989891a5462e627'
red = "\033[1;31m"
black1 = "\033[0m"
cyan = "\033[1;32m"
green = "\033[1;36m"

cautor = " "
csettingslang = "Settings"
cstartinviting = "Start inviting"
cexitlang = "Exit"
cchangetoken = "Change token"
clanguage = "Change language"
cback = "Back" 
cnumberofaction = 'Enter the number of action: '
cerrornumber = 'Error! Input correct number'
cnewtoken = 'Enter new token: '
csuccess = 'Success! '
cuserinvited = 'Users invited: '
centerchat = 'Enter chat: '
cdeletessesion = 'Delete session.session'
cnousers = 'List of users is empty'
cgetusers = 'Parse users from groups'
cuserparsed = 'Users added: '
cyouchat = 'Enter your chat: '
cerrorrstext = "Errors: "
centercount = 'Enter user count: '
cuploadingtext = 'Uploading...'
cuploaduserstext = 'Upload users from database'
csleeptimetext = 'Sleep time'
csleeptimechtext = 'Enter sleep time'
cdeletedatabase = 'Delete database'

def change():
	if csuccess == 'Успех!':
	        cautor = "   "
	        csettingslang = "Settings"
	        cstartinviting = "Start inviting"
	        cexitlang = "Exit"
	        cchangetoken = "Change token"
	        clanguage = "Change language"
	        cback = "Back" 
	        cnumberofaction = 'Enter the number of action: '
	        cerrornumber = 'Error! Input correct number'
	        cnewtoken = 'Enter new token: '
	        csuccess = 'Success!'
	        cuserinvited = 'Users invited: '
	        centerchat = 'Enter chat: '
	        cdeletessesion = 'Delete session.session'
	        cnousers = 'List of users is empty'
	        cgetusers = 'Parse users from groups'
	        cuserparsed = 'Users added: '
	        cyouchat = 'Enter your chat: '
	        cerrorrstext = "Errors: "
	        centercount = 'Enter user count: '
	        cuploadingtext = 'Uploading...'
	        cuploaduserstext = 'Upload users from database'
	        csleeptimetext = 'Sleep time'
	        csleeptimechtext = 'Enter sleep time'
	        cdeletedatabase = 'Delete database'

	    else:
	        cautor = "  "
	        csettingslang = "Настройки"
	        cstartinviting = "Начать приглашение"
	        cexitlang = "Выход"
	        cchangetoken = "Изменить токен"
	        clanguage = "Изменить язык"
	        cback = "Назад" 
	        cnumberofaction = 'Введите номер действия: '
	        cerrornumber = 'Ошибка! Введите валидное число!'
	        cnewtoken = 'Введите новый токен: '
	        csuccess = 'Успех!'
	        cuserinvited = 'Человек приглашено: '
	        centerchat = 'Введите название чата: '
	        cdeletessesion = 'Удалите session.session'
	        cnousers = 'Список пользователей пуст'
	        cgetusers = 'Парсить пользователей из групп'
	        cuserparsed = 'Добавлено пользователей: '
	        cyouchat = 'Введите свой чат: '
	        cerrorrstext = "Ошибок: "
	        centercount = 'Введите количество пользователей: '
	        cuploadingtext = 'Загрузка...'
	        cuploaduserstext = 'Загрузить пользователей из базы данных'
	        csleeptimechtext = 'Введите новую зaдержку'
	        csleeptimetext = 'Задержка'
	        cdeletedatabase = 'Удалить базу данных'
